# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db5d368b357e5b553bfa30dcfce9fae14c09419e75850c523479743ff54d8c24e9ef9c18b0b70921ec42cfb19e76f5d0dfa35e7eadb9c9fa8bd8d523d926cd9

test:
  secret_key_base: fb80cb0182a8f5ba4ddbbf284b66df71aa3bca91ccc229d4d8725e925474e6200dde251e652ecf3bffa3737ef30cebcb1254c65e7c4e534fbc11232b81f85c89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
